// rewards/index.js
export {
    extractReward,
    extractReward as extractStandUpReward,
    extractDuckReward,
    extractDuckStandReward,
    extractDuckWalkReward,
    resetDuckRewardState,
    extractG1Reward,
    extractG1StandReward,
    extractG1WalkReward,
    resetG1RewardState,
    getLastMotorOutcome,
    setLastMotorOutcome,
    clearMotorOutcome,
    resolveAdvantageFromOutcome,
    outcomeToJsonMessage,
    outcomeToStimPayload,
    outcomeToStimAmount,
    readStandHeights,
    REWARD_DEFAULTS,
    STANDUP_REWARD_DEFAULTS,
    MOTOR_OUTCOME_EXTRA,
    createRewardCurriculum,
    createTouchOutcome,
} from './rewards.js';