export const G1_ROBOT = {
    id: 'g1',
    name: 'Unitree G1',
    family: 'g1',
    basePath: '/unitree_g1',
    scene: 'scene.xml',
    task: 'stand',
    cmd: [0.4, 0, 0],
    headCmd: [0, 0, 0, 0],
    spawn: {
        x: 0,
        y: 0,
        z: 0.92,
        quat: [1, 0, 0, 0],
    },
    viewCam: {
        offset: [2.2, 1.25, 0.65],
        lookAtZ: 0,
        minDistance: 0.9,
        maxDistance: 8,
        fov: 50,
    },
    torsoBody: 'torso_link',
    headBody: 'head_link',
    headSite: 'imu_in_torso',
    chestAxis: 'x',
    headLocal: { x: 0.0039635, y: 0, z: 0.38 },
    headCam: {
        position: [0.06, 0.4, 0],
        rotation: [-0.18, -Math.PI / 2, 0],
        debug: false,
    },
    drag: { stiffness: 400, damping: 25, maxForce: 300 },
    sim: {
        inferHz: 50,
        playbackRate: 0.25,
        maxStepsPerFrame: 24,
        rewardEveryN: 1,
        rewardMinDtMs: 24,
    },
    stand: {
        wPosture: 0.55,
        wRise: 0.45,
        wSit: 0.18,
        wUpright: 0.22,
        wDrop: 0.35,
        wSuccess: 0.25,
        wVel: 0.006,
        wCtrl: 0.003,
        riseScale: 0.04,
        dropScale: 0.03,
        progressScale: 0.04,
        fallenFloor: -1.0,
        fallenLift: 0.0,
        headBelowWaistFloor: -1.0,
        fallMix: 0.25,
        walkGatePelvis: 0.70,
        walkGateHead: 0.98,
        walkGateUpright: 0.70,
        standWalkVx: 0.4,
        heightStand: 0.98,
        pelvisStand: 0.79,
        headStand: 1.22,
        pelvisSit: 0.35,
        pelvisFall: 0.12,
        headFall: 0.20,
        pelvisFloor: 0.05,
        headFloor: 0.12,
        onFloorUpright: 0.15,
        successUpright: 0.82,
        successPelvis: 0.74,
        successHead: 1.12,
    },
    reward: {
        fallenFloor: -1.0,
        wFall: 1.0,
    },
};

export default G1_ROBOT;