/** Official STAND2 / HOME_FRAME. Not model.qpos0. */
export const MICRODUCK_STAND2 = Object.freeze([
    0.0,
    -0.0873,
    -0.4579,
    -0.0049,
    0.4530,
    0.3491,
    0.3491,
    0.0,
    0.0,
    0.0,
    0.0873,
    0.4579,
    0.0049,
    -0.4530,
]);

export const MICRODUCK_JOINTS = Object.freeze([
    'left_hip_yaw',
    'left_hip_roll',
    'left_hip_pitch',
    'left_knee',
    'left_ankle',
    'neck_pitch',
    'head_pitch',
    'head_yaw',
    'head_roll',
    'right_hip_yaw',
    'right_hip_roll',
    'right_hip_pitch',
    'right_knee',
    'right_ankle',
]);

export const MICRODUCK_ROBOT = {
    id: 'microduck',
    name: 'MicroDuck',
    family: 'microduck',
    basePath: '/microduck/robot/microduck',
    scene: 'scene.xml',
    scenes: {
        default: 'scene.xml',
        walk: 'scene_walk.xml',
        standup: 'scene.xml',
    },
    task: 'walk',
    policy: {
        dir: '/microduck/policies',
        walk: '/microduck/policies/alpha_walking.onnx',
        stand: null,
        actionScale: 1.0,
        hz: 50,
        obsN: 61,
        actN: 14,
        gyroSensor: 'imu_ang_vel',
        floorPelvis: 0.07,
        floorUpright: 0.18,
        standPelvis: 0.10,
        standUpright: 0.70,
        pose: MICRODUCK_STAND2,
        joints: MICRODUCK_JOINTS,
    },
    sim: {
        inferHz: 50,
        playbackRate: 0.25,
        maxStepsPerFrame: 24,
        rewardEveryN: 1,
        rewardMinDtMs: 24,
    },
    cmd: [0, 0, 0],
    headCmd: [0, 0, 0, 0],
    spawn: {
        x: 0,
        y: 0,
        z: 0.125,
        quat: [1, 0, 0, 0],
    },
    viewCam: {
        offset: [0.55, 0.32, 0.18],
        lookAtZ: 0.08,
        minDistance: 0.22,
        maxDistance: 3.5,
        fov: 50,
    },
    torsoBody: 'trunk_base',
    headBody: 'jaw_soft',
    headCam: {
        position: [0.02, -0.08, 0],
        rotation: [Math.PI / 2, Math.PI, Math.PI / 2],
        debug: false,
    },
    headSite: 'head_camera',
    waistYawJoint: 'head_yaw',
    chestAxis: 'x',
    headLocal: { x: 0, y: 0, z: 0.08 },
    footBodies: ['ankle_l_v1', 'ankle_r_v1', 'left_foot', 'right_foot'],
    drag: { stiffness: 40, damping: 8, maxForce: 15 },
    stand: {
        pelvisFloor: 0.045,
        pelvisFall: 0.055,
        pelvisStand: 0.12,
        headFloor: 0.04,
        headFall: 0.06,
        headStand: 0.20,
        successPelvis: 0.10,
        successHead: 0.16,
        successUpright: 0.78,
        sideUpright: 0.45,
        fallUpright: 0.22,
        floorUpright: 0.18,
        standWalkVx: 0.15,
        onFloorUpright: 0.18,
    },
    geneOpts: {
        limits: { wUpright: 0.5, wSide: 0.9 },
        roll: { pelvisLo: 0.03, pelvisHi: 0.10 },
        quad: {
            pelvisLo: 0.04,
            pelvisHi: 0.10,
            headLo: 0.06,
            headHi: 0.16,
        },
        crawl: { pelvisLo: 0.04, pelvisHi: 0.10, forwardScale: 0.015 },
    },
};

export default MICRODUCK_ROBOT;